// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "VectLite",
    platforms: [
        .macOS(.v12),
        .iOS(.v15),
        .tvOS(.v15),
        .watchOS(.v8),
    ],
    products: [
        .library(name: "VectLite", targets: ["VectLite"]),
    ],
    targets: [
        // The binary XCFramework containing the native Rust library.
        // Build with: ./build-xcframework.sh
        .binaryTarget(
            name: "vectliteFFI",
            path: "VectLiteFFI.xcframework"
        ),
        // Swift wrapper generated by UniFFI.
        .target(
            name: "VectLite",
            dependencies: ["vectliteFFI"],
            path: "Sources/VectLite"
        ),
        .testTarget(
            name: "VectLiteTests",
            dependencies: ["VectLite"],
            path: "Tests/VectLiteTests"
        ),
    ]
)
