[package]
name = "vectlite-node"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Node.js bindings for vectlite."
homepage = "https://vectlite.mcsedition.org/"
repository = "https://github.com/mcsedition-hub/vectlite"
documentation = "https://vectlite.mcsedition.org/"
build = "build.rs"

[lib]
name = "vectlite_node"
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.5.2", default-features = false, features = ["napi8"] }
napi-derive = "3.3.0"
serde_json = "1.0"
vectlite = { package = "vectlite-core", path = "../../crates/vectlite-core" }

[build-dependencies]
napi-build = "2.2.3"
