[package]
name = "vectlite-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI for inspecting and validating vectlite databases."
homepage = "https://vectlite.mcsedition.org/"
repository = "https://github.com/mcsedition-hub/vectlite"
documentation = "https://vectlite.mcsedition.org/"

[[bin]]
name = "vectlite"
path = "src/main.rs"

[dependencies]
vectlite = { package = "vectlite-core", path = "../vectlite-core" }
